---
- hosts: rabbitmq-master
  remote_user: molecule
  become: true
  any_errors_fatal: true
  roles:
    - ansible-role-erlang
    - ansible-role-rabbitmq

- hosts: rabbitmq-slave
  remote_user: molecule
  become: true
  any_errors_fatal: true
  roles:
    - ansible-role-erlang
    - ansible-role-rabbitmq
